import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import dynamic from "next/dynamic";

// import Header from "LandingPage/Header";
// import Footer from "LandingPage/Footer";

const Header = dynamic(
  async () => {
    // Sleep, for demoing purposes
    await new Promise((res) => setTimeout(res, 1500));
    // @ts-ignore
    return await import("LandingPage/Header");
  },
  {
    ssr: false,
    loading: ({ error }) => {
      if (error) {
        return <h1>{error.message}</h1>;
      }
      return <h1>loading...</h1>;
    },
  }
);

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Link href="/home">
        <a>About Us</a>
      </Link>
    </div>
  );
}
